### ISSUE TITLE
Dissimilarity Index as in Meyer, Pebesma 2021

### ISSUE THREAD

**Issue by sheffe** [benjilu/forestError#7]
I ran across this very nice paper recently: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13650

It proposes a very intuitive metric for measuring distance from a test observation's X values to the predictor space of the training set and calls it a Dissimilarity Index. 

This specific application is for spatial models with a corresponding block-bootstrap design, but the same calculation could be done with in-bag/out-of-bag splits using the data ingested by forestError.

Thought you might find this interesting -- I would consider it very germane to the same tasks where I'm using forestError and might be a worthwhile addition to the exported data.

**Comment by benjilu** [comment]
Thanks for the interesting reference! I will continue mulling over it.
